set(TARGET_SPECULATIVE llama-speculative-simple)
add_executable(${TARGET_SPECULATIVE} speculative-simple.cpp)
install(TARGETS ${TARGET_SPECULATIVE} RUNTIME)
target_link_libraries(${TARGET_SPECULATIVE} PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET_SPECULATIVE} PRIVATE cxx_std_17)

set(TARGET_NGRAM ngram-spec-simple)
add_executable(${TARGET_NGRAM} ngram-spec-simple.cpp)
install(TARGETS ${TARGET_NGRAM} RUNTIME)
target_link_libraries(${TARGET_NGRAM} PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET_NGRAM} PRIVATE cxx_std_17)
