#include "arg.h"
#include "common.h"
#include "sampling.h"
#include "log.h"
#include "llama.h"
#include "ngram-cache.h"

#include <algorithm>
#include <cstdio>
#include <cstring>
#include <random>
#include <set>
#include <string>
#include <vector>
#include <map>
#include <numeric>

#define SPEC_VOCAB_MAX_SIZE_DIFFERENCE  128
#define SPEC_VOCAB_CHECK_START_TOKEN_ID 5

struct seq_draft {
    bool active   = false;
    bool drafting = false;
    bool skip     = false;

    int i_batch_dft = 0;
    std::vector<int> i_batch_tgt;

    std::vector<llama_token> tokens;
    std::vector<std::vector<llama_token_data>> dists;

    struct common_sampler * smpl = nullptr;
};

// Function to generate draft sequences from the draft model
void generate_draft_sequences(int n_draft, std::vector<seq_draft>& drafts, llama_context* ctx_dft, llama_batch& batch_dft, 
                               llama_batch& batch_tgt, int& n_past_cur, int& n_drafted, float p_draft_split, int& n_past_tgt) {
    int n_seq_cur = drafts.size(); // Initialize n_seq_cur to the number of drafts

    // Sample n_draft tokens from the draft model using tree-based sampling
    for (int i = 0; i < n_draft; ++i) {
        batch_dft.n_tokens = 0; // Reset the number of tokens in the draft batch

        for (int s = 0; s < drafts.size(); ++s) {
            drafts[s].skip = false; // Reset the skip flag for each draft
        }

        for (int s = 0; s < drafts.size(); ++s) {
            if (!drafts[s].drafting || drafts[s].skip) {
                continue; // Skip if the draft is not active or marked to skip
            }

            common_sampler_sample(drafts[s].smpl, ctx_dft, drafts[s].i_batch_dft, true); // Sample from the draft model
            const auto* cur_p = common_sampler_get_candidates(drafts[s].smpl); // Get the candidates generated by the draft model

            // Log the candidates for debugging
            for (int k = 0; k < std::min(static_cast<size_t>(cur_p->size), drafts.size() + 3); ++k) {
                LOG_DBG(" - draft candidate %3d for seq %3d, pos %3d: %6d (%8.3f) '%s'\n",
                        k, s, i, cur_p->data[k].id, cur_p->data[k].p, common_token_to_piece(ctx_dft, cur_p->data[k].id).c_str());
            }

            std::vector<int> sa(1, s); // Store the current sequence index

            // Attempt to split the branch if the probability is high enough
            for (int f = 1; f < 8; ++f) {
                if (n_seq_cur < drafts.size() && cur_p->data[f].p > p_draft_split) {
                    LOG_DBG("splitting seq %3d into %3d\n", s, n_seq_cur);

                    llama_kv_self_seq_rm(ctx_dft, n_seq_cur, -1, -1);
                    llama_kv_self_seq_cp(ctx_dft, s, n_seq_cur, -1, -1);

                    // All previous tokens from this branch are now also part of the new branch
                    for (int t = 0; t < batch_tgt.n_tokens; ++t) {
                        for (int p = 0; p < batch_tgt.n_seq_id[t]; ++p) {
                            if (batch_tgt.seq_id[t][p] == s) {
                                batch_tgt.seq_id[t][batch_tgt.n_seq_id[t]] = n_seq_cur;
                                batch_tgt.n_seq_id[t]++;
                                break;
                            }
                        }
                    }

                    // Copy the draft state
                    drafts[n_seq_cur].active = true;
                    drafts[n_seq_cur].drafting = true;
                    drafts[n_seq_cur].skip = true;

                    drafts[n_seq_cur].tokens = drafts[s].tokens;
                    drafts[n_seq_cur].dists = drafts[s].dists;
                    drafts[n_seq_cur].i_batch_dft = drafts[s].i_batch_dft;
                    drafts[n_seq_cur].i_batch_tgt = drafts[s].i_batch_tgt;

                    if (drafts[n_seq_cur].smpl) {
                        common_sampler_free(drafts[n_seq_cur].smpl);
                    }
                    drafts[n_seq_cur].smpl = common_sampler_clone(drafts[s].smpl);

                    sa.push_back(n_seq_cur); // Add the new sequence index to the list
                    n_seq_cur++; // Increment the current sequence count
                } else {
                    break; // Exit the loop if the probability condition is not met
                }
            }

            // Add drafted token for each sequence
            for (int is = 0; is < (int)sa.size(); ++is) {
                const llama_token id = cur_p->data[is].id; // Get the candidate token ID
                const int s = sa[is]; // Get the corresponding draft sequence index

                common_sampler_accept(drafts[s].smpl, id, true); // Accept the drafted token
                drafts[s].tokens.push_back(id); // Store the drafted token in the sequence
                drafts[s].dists.push_back({cur_p->data, cur_p->data + cur_p->size}); // Store the candidate probabilities

                // Add unique drafted tokens to the target batch
                drafts[s].i_batch_tgt.push_back(batch_tgt.n_tokens); // Keep track of the index for the target batch
                common_batch_add(batch_tgt, id, n_past_tgt + i + 1, { s }, true); // Add the token to the target batch for decoding

                // Add the token to the batch for batched decoding with the draft model
                drafts[s].i_batch_dft = batch_dft.n_tokens; // Update the index for the draft batch
                common_batch_add(batch_dft, id, n_past_cur, { s }, true); // Add the token to the draft batch

                if (batch_tgt.n_tokens > n_draft) {
                    drafts[s].drafting = false; // Mark the draft as no longer active if it exceeds the limit
                }
            }
        }

        // No sequence is drafting anymore
        if (batch_dft.n_tokens == 0) {
            break; // Exit the loop if no tokens are left to draft
        }

        // Evaluate the drafted tokens on the draft model
        llama_decode(ctx_dft, batch_dft);
        ++n_past_cur; // Increment the count of past tokens processed
        ++n_drafted; // Increment the count of drafted tokens

        if (batch_tgt.n_tokens > n_draft) {
            break; // Exit if the target batch exceeds the draft limit
        }
    }
}

int main(int argc, char ** argv) {
    common_params params;

    // needed to get candidate probs even for temp <= 0.0
    params.sampling.n_probs = 128;

    if (!common_params_parse(argc, argv, params, LLAMA_EXAMPLE_SPECULATIVE)) {
        return 1;
    }

    if (params.n_predict < -1) {
        LOG_ERR("%s: --n-predict must be >= -1\n", __func__);
        return 1;
    }

    common_init();

    if (params.speculative.model.empty()) {
        LOG_ERR("%s: --model-draft is required\n", __func__);
        return 1;
    }

    // Initialize n-gram cache
    common_ngram_cache ngram_cache;

    // max number of parallel drafting sequences (i.e. tree branches)
    const int n_seq_dft = params.n_parallel;

    // probability threshold for splitting a draft branch (only for n_seq_dft > 1)
    const float p_draft_split = params.speculative.p_split;

    std::default_random_engine rng(params.sampling.seed == LLAMA_DEFAULT_SEED ? std::random_device()() : params.sampling.seed);
    std::uniform_real_distribution<> u_dist;

    // init llama.cpp
    llama_backend_init();
    llama_numa_init(params.numa);

    llama_model * model_tgt = NULL;
    llama_model * model_dft = NULL;

    llama_context * ctx_tgt = NULL;
    llama_context * ctx_dft = NULL;

    // load the target model
    common_init_result llama_init_tgt = common_init_from_params(params);

    model_tgt = llama_init_tgt.model.get();
    ctx_tgt   = llama_init_tgt.context.get();

    // load the draft model
    params.devices = params.speculative.devices;
    params.model = params.speculative.model;
    params.n_gpu_layers = params.speculative.n_gpu_layers;
    if (params.speculative.cpuparams.n_threads > 0) {
        params.cpuparams.n_threads = params.speculative.cpuparams.n_threads;
    }

    params.cpuparams_batch.n_threads = params.speculative.cpuparams_batch.n_threads;
    common_init_result llama_init_dft = common_init_from_params(params);

    model_dft = llama_init_dft.model.get();
    ctx_dft   = llama_init_dft.context.get();

    const llama_vocab * vocab_tgt = llama_model_get_vocab(model_tgt);
    const llama_vocab * vocab_dft = llama_model_get_vocab(model_dft);

    const bool vocab_type_tgt = llama_vocab_type(vocab_tgt);
    LOG_DBG("vocab_type tgt: %d\n", vocab_type_tgt);

    const bool vocab_type_dft = llama_vocab_type(vocab_dft);
    LOG_DBG("vocab_type dft: %d\n", vocab_type_dft);

    if (vocab_type_tgt != vocab_type_dft) {
        LOG_ERR("%s: draft model vocab type must match target model to use speculation but ", __func__);
        LOG_ERR("vocab_type_dft = %d while vocab_type_tgt = %d\n", vocab_type_dft, vocab_type_tgt);
        return 1;
    }

    if (
        llama_vocab_get_add_bos(vocab_tgt) != llama_vocab_get_add_bos(vocab_dft) ||
        llama_vocab_get_add_eos(vocab_tgt) != llama_vocab_get_add_eos(vocab_dft) ||
        llama_vocab_bos(vocab_tgt) != llama_vocab_bos(vocab_dft) ||
        llama_vocab_eos(vocab_tgt) != llama_vocab_eos(vocab_dft)
    ) {
        LOG_ERR("%s: draft model special tokens must match target model to use speculation\n", __func__);
        return 1;
    }

    {
        const int n_vocab_tgt = llama_vocab_n_tokens(vocab_tgt);
        const int n_vocab_dft = llama_vocab_n_tokens(vocab_dft);
        const int vocab_diff  = n_vocab_tgt > n_vocab_dft
            ? n_vocab_tgt - n_vocab_dft
            : n_vocab_dft - n_vocab_tgt;

        if (vocab_diff > SPEC_VOCAB_MAX_SIZE_DIFFERENCE) {
            LOG_ERR("%s: draft model vocab must closely match target model to use speculation but ", __func__);
            LOG_ERR("target vocab size %d does not match draft vocab size %d - difference %d, max allowed %d\n",
                    n_vocab_tgt, llama_vocab_n_tokens(vocab_dft), vocab_diff, SPEC_VOCAB_MAX_SIZE_DIFFERENCE);
            return 1;
        }

        for (int i = SPEC_VOCAB_CHECK_START_TOKEN_ID; i < std::min(n_vocab_tgt, n_vocab_dft); ++i) {
            const char * token_text_tgt = llama_vocab_get_text(vocab_tgt, i);
            const char * token_text_dft = llama_vocab_get_text(vocab_dft, i);
            if (std::strcmp(token_text_tgt, token_text_dft) != 0) {
                LOG_ERR("%s: draft model vocab must match target model to use speculation but ", __func__);
                LOG_ERR("token %d content differs - target '%s', draft '%s'\n", i,
                        common_token_to_piece(ctx_tgt, i).c_str(),
                        common_token_to_piece(ctx_dft, i).c_str());
                return 1;
            }
        }
    }

    // Tokenize the prompt
    std::vector<llama_token> inp;
    inp = common_tokenize(ctx_tgt, params.prompt, true, true);

    const int max_context_size     = llama_n_ctx(ctx_tgt);
    const int max_tokens_list_size = max_context_size - 4;

    if ((int) inp.size() > max_tokens_list_size) {
        LOG_ERR("%s: prompt too long (%d tokens, max %d)\n", __func__, (int) inp.size(), max_tokens_list_size);
        return 1;
    }

    // Log the first 10 tokens of the input
    LOG("\nFirst 10 tokens of the input:\n");
    for (int i = 0; i < std::min(10, (int) inp.size()); ++i) {
        LOG("Token %d: ID=%d, Text='%s'\n", i, inp[i], common_token_to_piece(ctx_tgt, inp[i]).c_str());
    }

    // Fill the n-gram cache with tokens from the prompt
    const auto t_ngram_cache_start = ggml_time_us(); // Start timing
    common_ngram_cache_update(ngram_cache, LLAMA_NGRAM_MIN, LLAMA_NGRAM_MAX, inp, inp.size(), false);
    const auto t_ngram_cache_end = ggml_time_us(); // End timing

    // Log the time taken to build the n-gram cache
    LOG_INF("Time taken to build n-gram cache from the prompt: %.3f seconds\n", (t_ngram_cache_end - t_ngram_cache_start) / 1e6f);

    // Log the contents of the n-gram cache
    LOG("\nContents of the n-gram cache:\n");
    std::map<std::string, std::vector<std::string>> sorted_entries;

    for (const auto& entry : ngram_cache) {
        // Detokenize the n-gram
        std::string ngram_text;
        for (const auto& token : entry.first.tokens) {
            if (token != -1) {
                ngram_text += common_token_to_piece(ctx_tgt, token) + " (" + std::to_string(token) + ") "; // Include token ID
            }
        }
        ngram_text = ngram_text.substr(0, ngram_text.size() - 1); // Remove trailing space

        // Prepare candidates
        std::vector<std::string> candidates_text;
        for (const auto& candidate : entry.second) {
            if (candidate.first != -1) {
                candidates_text.push_back(common_token_to_piece(ctx_tgt, candidate.first) + " (" + std::to_string(candidate.first) + ")"); // Detokenize candidate and include ID
            }
        }

        // Store in the map
        sorted_entries[ngram_text] = candidates_text; // Map n-gram text to its candidates
    }

    // Log sorted entries, limiting to the first 50
    int count = 0;
    for (const auto& [ngram, candidates] : sorted_entries) {
        LOG("%s → ", ngram.c_str());
        for (const auto& candidate : candidates) {
            LOG("%s ", candidate.c_str());
        }
        LOG("\n");

        count++;
        if (count >= 100) {
            break; // Limit to first 50 entries
        }
    }

    const int n_input = inp.size();

    const auto t_enc_start = ggml_time_us();

    // eval the prompt with both models
    llama_decode(ctx_tgt, llama_batch_get_one( inp.data(), n_input - 1));
    llama_decode(ctx_tgt, llama_batch_get_one(&inp.back(),           1));
    llama_decode(ctx_dft, llama_batch_get_one( inp.data(), n_input));

    const auto t_enc_end = ggml_time_us();

    // the 2 models should have the same vocab
    //GGML_ASSERT(n_vocab == llama_vocab_n_tokens(model_dft));

    // how many tokens to draft each time
    int n_draft = params.speculative.n_max;

    int n_predict = 0;
    int n_drafted = 0;
    int n_accept  = 0;

    int n_past_tgt = inp.size();
    int n_past_dft = inp.size();

    // used to determine end of generation
    bool has_eos = false;

    // target model sampling context (reuse the llama_context's sampling instance)
    struct common_sampler * smpl = common_sampler_init(model_tgt, params.sampling);

    // draft sequence data
    std::vector<seq_draft> drafts(n_seq_dft);

    for (int s = 0; s < n_seq_dft; ++s) {
        // allocate llama_sampler for each draft sequence
        drafts[s].smpl = common_sampler_init(model_dft, params.sampling);
    }

    llama_batch batch_dft = llama_batch_init(llama_n_batch(ctx_dft), 0, 1);
    llama_batch batch_tgt = llama_batch_init(llama_n_batch(ctx_tgt), 0, n_seq_dft);

    const auto t_dec_start = ggml_time_us();

    // sample from the last token of the prompt
    drafts[0].i_batch_tgt.resize(1);
    drafts[0].i_batch_tgt[0] = 0;

    std::vector<double> all_draft_times;
    std::vector<double> all_target_decode_times;

    while (true) {
        std::set<int> active_seqs = {};

        // print current draft sequences
        for (int s = 0; s < n_seq_dft; ++s) {
            if (!drafts[s].active) {
                continue;
            }

            active_seqs.insert(s);
            const auto & tokens = drafts[s].tokens;

            LOG_DBG("draft %d: %s\n", s, string_from(ctx_dft, tokens).c_str());
        }

        int i_dft  = 0;
        int s_keep = 0;

        llama_token token_id;
        std::string token_str;

        // loop until we fail to accept a drafted token or we run out of drafted tokens
        while (true) {

            // check if the target token matches any of the drafts
            // for stochastic sampling, attempt to match the token with the drafted tokens
            {
                bool accept = false;

                // only-greedy, simplifies the code
                // sample from the target model
                LOG_DBG("sampling target: s_keep = %3d, i_dft = %3d, i_batch_tgt = %3d\n", s_keep, i_dft, drafts[s_keep].i_batch_tgt[i_dft]);
                token_id = common_sampler_sample(smpl, ctx_tgt, drafts[s_keep].i_batch_tgt[i_dft]);

                common_sampler_accept(smpl, token_id, true);

                token_str = common_token_to_piece(ctx_tgt, token_id);

                for (int s = 0; s < n_seq_dft; ++s) {
                    if (!drafts[s].active) {
                        continue;
                    }

                    if (i_dft < (int) drafts[s].tokens.size() && token_id == drafts[s].tokens[i_dft]) {
                        LOG_DBG("the sampled target token matches the %dth drafted token of sequence %d (%d, '%s') - accepted\n", i_dft, s, token_id, token_str.c_str());

                        s_keep = s;
                        accept = true;
                    } else {
                        drafts[s].active = false;
                    }
                }

                if (llama_vocab_is_eog(vocab_tgt, token_id)) {
                    has_eos = true;
                }
                ++n_predict;

                if (accept) {
                    ++n_accept;
                    ++n_past_tgt;
                    ++n_past_dft;
                    ++i_dft;
                    if (params.use_color) {
                        // Color token according to its origin sequence
                        LOG("\u001b[%dm%s\u001b[37m", (36 - s_keep % 6), token_str.c_str());
                    } else {
                        LOG("%s", token_str.c_str());
                    }
                    continue;
                } else {
                    LOG("%s", token_str.c_str());
                    break;
                }
            }
        }

        LOG_DBG("the sampled target token (%d, '%s') did not match, or we ran out of drafted tokens\n", token_id, token_str.c_str());

        // TODO: simplify
        LOG_DBG("keeping sequence %d, n_past_tgt = %d, n_past_dft = %d\n", s_keep, n_past_tgt, n_past_dft);

        llama_kv_self_seq_keep(ctx_dft, s_keep);
        llama_kv_self_seq_cp  (ctx_dft, s_keep, 0, -1, -1);
        llama_kv_self_seq_keep(ctx_dft, 0);

        llama_kv_self_seq_rm  (ctx_tgt, s_keep, n_past_tgt, -1);
        llama_kv_self_seq_keep(ctx_tgt, s_keep);
        llama_kv_self_seq_cp  (ctx_tgt, s_keep, 0, -1, -1);
        llama_kv_self_seq_keep(ctx_tgt, 0);

        for (int s = 0; s < n_seq_dft; ++s) {
            drafts[s].active = false;
            drafts[s].tokens.clear();
            drafts[s].i_batch_tgt.clear();
            drafts[s].dists.clear();
        }
        // note: will be erased after the speculation phase
        drafts[0].tokens.push_back(token_id);
        drafts[0].dists.push_back(std::vector<llama_token_data>());
        drafts[0].i_batch_tgt.push_back(0);

        common_batch_clear(batch_dft);
        common_batch_add  (batch_dft, token_id, n_past_dft, { 0 }, true);

        llama_kv_self_seq_rm(ctx_dft, 0, n_past_dft, -1);
        // LOG_DBG("dft batch: %s\n", LOG_BATCH_TOSTR_PRETTY(ctx_dft, batch_dft).c_str());
        llama_decode(ctx_dft, batch_dft);

        ++n_past_dft;

        if ((params.n_predict >= 0 && n_predict > params.n_predict) || has_eos) {
            break;
        }

        if (drafts[0].smpl) {
            common_sampler_free(drafts[0].smpl);
        }
        drafts[0].smpl = common_sampler_clone(smpl);

        int n_seq_cur  = 1;
        int n_past_cur = n_past_dft;

        for (int s = 0; s < n_seq_dft; ++s) {
            drafts[s].active   = false;
            drafts[s].drafting = false;
        }
        drafts[0].active      = true;
        drafts[0].drafting    = true;
        drafts[0].i_batch_dft = 0;

        common_batch_clear(batch_tgt);
        common_batch_add  (batch_tgt, drafts[0].tokens[0], n_past_tgt, { 0 }, true);

        // sample n_draft tokens from the draft model using tree-based sampling
        const auto t_draft_gen_start = ggml_time_us(); // Start timing
        generate_draft_sequences(n_draft, drafts, ctx_dft, batch_dft, batch_tgt, n_past_cur, n_drafted, p_draft_split, n_past_tgt);
        const auto t_draft_gen_end = ggml_time_us(); // End timing

        // Calculate the average time taken per draft in milliseconds
        double average_time_per_draft = (t_draft_gen_end - t_draft_gen_start) / 1e3 / n_draft;

        // Log the time taken to generate draft sequences in the new format
        LOG_INF("[sampling: %.3f ms]\n", average_time_per_draft);

        all_draft_times.push_back(average_time_per_draft);

        // evaluate the target model on the drafted tokens
        {
            llama_kv_self_seq_keep(ctx_tgt, 0);
            for (int s = 1; s < n_seq_dft; ++s) {
                llama_kv_self_seq_cp(ctx_tgt, 0, s, -1, -1);
            }

            // LOG_DBG("target batch: %s\n", LOG_BATCH_TOSTR_PRETTY(ctx_tgt, batch_tgt).c_str());
            const auto ctx_tgt_start_time = ggml_time_us(); // Start timing
            llama_decode(ctx_tgt, batch_tgt);
            const auto ctx_tgt_end_time = ggml_time_us(); // End timing
            double average_time_per_target_decode = (ctx_tgt_end_time - ctx_tgt_start_time) / 1e3 / n_seq_dft;
            LOG_INF("[TF: %.3f ms]\n", average_time_per_target_decode);
            all_target_decode_times.push_back(average_time_per_target_decode);
            ++n_past_tgt;
        }

        // the first token is always proposed by the target model before the speculation loop so we erase it here
        for (int s = 0; s < n_seq_dft; ++s) {
            if (!drafts[s].active) {
                continue;
            }

            drafts[s].tokens.erase(drafts[s].tokens.begin());
            drafts[s].dists.erase(drafts[s].dists.begin());
        }
    }

    auto t_dec_end = ggml_time_us();

    LOG("\n\n");
    LOG_INF("Average draft model forward + sampling time: %.3f ms\n", std::accumulate(all_draft_times.begin(), all_draft_times.end(), 0.0) / all_draft_times.size());
    LOG_INF("Average target model forward time: %.3f ms\n", std::accumulate(all_target_decode_times.begin(), all_target_decode_times.end(), 0.0) / all_target_decode_times.size());
    LOG_INF("encoded %4d tokens in %8.3f seconds, speed: %8.3f t/s\n", n_input,   (t_enc_end - t_enc_start) / 1e6f, inp.size() / ((t_enc_end - t_enc_start) / 1e6f));
    LOG_INF("decoded %4d tokens in %8.3f seconds, speed: %8.3f t/s\n", n_predict, (t_dec_end - t_dec_start) / 1e6f, n_predict  / ((t_dec_end - t_dec_start) / 1e6f));

    LOG_INF("\n");
    LOG_INF("n_draft   = %d\n", n_draft);
    LOG_INF("n_predict = %d\n", n_predict);
    LOG_INF("n_drafted = %d\n", n_drafted);
    LOG_INF("n_accept  = %d\n", n_accept);
    LOG_INF("accept    = %.3f%%\n", 100.0f * n_accept / n_drafted);

    LOG_INF("\n");
    LOG_INF("draft:\n\n");
    // TODO: print sampling/grammar timings for all drafts
    llama_perf_context_print(ctx_dft);

    LOG_INF("\n");
    LOG_INF("target:\n\n");
    common_perf_print(ctx_tgt, smpl);

    common_sampler_free(smpl);
    for (int s = 0; s < n_seq_dft; ++s) {
        common_sampler_free(drafts[s].smpl);
    }

    llama_batch_free(batch_dft);

    llama_backend_free();

    LOG("\n\n");

    return 0;
}
