// AUTO-GENERATED - DO NOT MODIFY
// Generated by cbindgen from DraftRetriever


#ifndef DRAFT_RETRIEVER_H
#define DRAFT_RETRIEVER_H

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace draftretriever {

struct SearchResults {
  int32_t **token_lists;
  uintptr_t *token_counts;
  uintptr_t list_count;
  int32_t **attn_mask;
  uintptr_t attn_rows;
  uintptr_t attn_cols;
  int32_t *tree_indices;
  uintptr_t tree_count;
  int32_t *position_ids;
  uintptr_t position_count;
  int32_t **retrieve_indices;
  uintptr_t *retrieve_counts;
  uintptr_t retrieve_count;
};

extern "C" {

extern int32_t libsais_int(const int32_t *data,
                           int32_t *suffix_array,
                           int32_t data_len,
                           int32_t suffix_array_extra_space,
                           int32_t symbol_frequency_table);

PyResult draftretriever(Python _py, const PyModule *m);

Reader *draftretriever_create_reader(const char *path);

void draftretriever_free_reader(Reader *reader);

Writer *draftretriever_create_writer(const char *path, uintptr_t max_chunk_len, int32_t vocab_size);

void draftretriever_free_writer(Writer *writer);

int draftretriever_add_entry(Writer *writer_ptr, const int32_t *tokens, uintptr_t token_count);

int draftretriever_finalize_writer(Writer *writer_ptr);

int draftretriever_search(Reader *reader_ptr,
                          const int32_t *prefix,
                          uintptr_t prefix_len,
                          int32_t choices,
                          int32_t k,
                          int32_t long_,
                          SearchResults *results);

void draftretriever_free_search_results(SearchResults *results);

int draftretriever_build_index(const int32_t *tokens,
                               uintptr_t token_count,
                               const char *path,
                               int32_t vocab_size);

}  // extern "C"

}  // namespace draftretriever

#endif  // DRAFT_RETRIEVER_H
